services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: mom-rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # painel web: http://localhost:15672 (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
